os: linux 
arch: ppc64le 
dist: bionic
sudo: required

env:
  global:
    - APK_TOOLS_URI="https://github.com/alpinelinux/apk-tools/releases/download/v2.10.3/apk-tools-2.10.3-ppc64le-linux.tar.gz"
    - APK_TOOLS_SHA256=75311787324dd56106b36d57cc33bcdacb8d089dbcd270669dab8d7eb76175d8

before_install:
  - wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.11.0/alpine-chroot-install
  - echo 'df472cbd2dc93eb0b3126d06209363c4fc328ea3' alpine-chroot-install | sha1sum -c
  - sudo sh ./alpine-chroot-install -k 'ARCH CI QEMU_EMULATOR TRAVIS_.* CC' -p "$ALPINE_PACKAGES"

jobs:
  include:
    - name: Coding style check
      language: minimal
      env:
        - ALPINE_PACKAGES=clang
      script:
        - /alpine/enter-chroot clang-format wob.c test.c --output-replacements-xml | (! grep '</replacement>' 1>/dev/null)
    - &test
      name: Test GCC
      language: minimal
      env:
        - ALPINE_PACKAGES="wayland-protocols wayland-dev meson gcc musl-dev binutils"
        - CC=gcc
      script:
        - /alpine/enter-chroot meson build
        - /alpine/enter-chroot ninja -C build
        - /alpine/enter-chroot meson test -C build
      after_failure:
        - cat build/meson-logs/meson-log.txt
    - <<: *test
      name: Test Clang
      env:
        - ALPINE_PACKAGES="wayland-protocols wayland-dev meson clang musl-dev binutils libc-dev"
        - CC=clang